Move build-related directories into sorc
NOAA-EMC/rrfs-workflow pull request #20
Opened 2023-07-15 23:09 UTC by chan-hoo

## DESCRIPTION OF CHANGES:

- Move the build-related directories such as `build`, `include`, `lib`, `lib64`, and `share` into the `sorc` directory.
- As a result, the `exec` directory is only added to the home directory once the build step is complete.

## TESTS CONDUCTED:

- On machines/platforms:

- [x] WCOSS2
- [ ] Hera
- [ ] Orion
- [ ] Jet

- Test cases:

- [x] Non-DA engineering test
- [ ] Sample script:

## ISSUE:

- Fixes the issue(s) mentioned in #19

2023-07-16 04:34 UTC, ShunLiu-NOAA approved these changes

2023-07-17 14:03 UTC, BenjaminBlake-NOAA approved these changes

2023-07-17 14:34 UTC, MatthewPyle-NOAA requested changes
Was about to approve, then noticed that "--move" was removed from devbuild.sh.  We need to preserve the ability to build the executables, and move them to the final exec/ directory as two separate steps.  Is an EE2 requirement.  The "--move" option was used to facilitate this functionality.

2023-07-17 15:15 UTC, chan-hoo commented
@MatthewPyle-NOAA, Fixed!

2023-07-17 15:21 UTC, MatthewPyle-NOAA approved these changes
Thanks for reverting that change @chan-hoo.  Will approve and merge now.

2023-07-17 15:21 UTC, merged